IF COL_LENGTH(N'dbo.Tenants', N'RowId') IS NULL
BEGIN
    ALTER TABLE dbo.Tenants ADD RowId BIGINT IDENTITY(1,1) NOT NULL;
END;
GO

IF COL_LENGTH(N'dbo.Users', N'RowId') IS NULL
BEGIN
    ALTER TABLE dbo.Users ADD RowId BIGINT IDENTITY(1,1) NOT NULL;
END;
GO

IF COL_LENGTH(N'dbo.TenantUsers', N'RowId') IS NULL
BEGIN
    ALTER TABLE dbo.TenantUsers ADD RowId BIGINT IDENTITY(1,1) NOT NULL;
END;
GO

IF COL_LENGTH(N'dbo.Branches', N'RowId') IS NULL
BEGIN
    ALTER TABLE dbo.Branches ADD RowId BIGINT IDENTITY(1,1) NOT NULL;
END;
GO

IF COL_LENGTH(N'dbo.BranchOrderSettings', N'RowId') IS NULL
BEGIN
    ALTER TABLE dbo.BranchOrderSettings ADD RowId BIGINT IDENTITY(1,1) NOT NULL;
END;
GO

IF COL_LENGTH(N'dbo.MenuCategories', N'RowId') IS NULL
BEGIN
    ALTER TABLE dbo.MenuCategories ADD RowId BIGINT IDENTITY(1,1) NOT NULL;
END;
GO

IF COL_LENGTH(N'dbo.MenuItems', N'RowId') IS NULL
BEGIN
    ALTER TABLE dbo.MenuItems ADD RowId BIGINT IDENTITY(1,1) NOT NULL;
END;
GO

IF COL_LENGTH(N'dbo.BranchTables', N'RowId') IS NULL
BEGIN
    ALTER TABLE dbo.BranchTables ADD RowId BIGINT IDENTITY(1,1) NOT NULL;
END;
GO

IF COL_LENGTH(N'dbo.Orders', N'RowId') IS NULL
BEGIN
    ALTER TABLE dbo.Orders ADD RowId BIGINT IDENTITY(1,1) NOT NULL;
END;
GO

IF COL_LENGTH(N'dbo.OrderItems', N'RowId') IS NULL
BEGIN
    ALTER TABLE dbo.OrderItems ADD RowId BIGINT IDENTITY(1,1) NOT NULL;
END;
GO
